### ISSUE TITLE
missing zookeeper service

### ISSUE THREAD

**Issue by spham** [sleighzy/ansible-kafka#14]
hi
just see only copy template without anything to start zookeeper service

we should have

bin/zookeeper-server-start.sh config/zookeeper.properties

on centos

we have

sudo systemctl start zookeeper
Mot de passe : 
Failed to start zookeeper.service: Unit not found.

with kafka-scala versison

regards

**Comment by sleighzy** [comment]
Hi @spham 

This role is intended for managing Kafka, so is expected to be deployed with an already existing ZooKeeper cluster. As per the README file I have another role for running ZooKeeper, see https://galaxy.ansible.com/sleighzy/zookeeper and https://github.com/sleighzy/ansible-zookeeper which will create that ZooKeeper service etc.

If you need to run ZooKeeper, and don't already have it installed, then I recommend including the ZooKeeper role I linked above to your playbook as well.

I'll review further this ZooKeeper template as may just need to update my docs to state that although this is configured as it ships with the default Kafka installation this role is not intended to handle both deployments.

**Comment by spham** [comment]
Ok but the latest version not need have both separately

**Comment by sleighzy** [comment]
Hi @spham . That's been available for a while now and their quickstart docs used to indicate it could be used to easily start an instance for testing purposes. You can take my code base and add that in for your own purposes, but if you instead use my other ZooKeeper role as well it'll actually install a proper service for it, amongst other things and is pretty easy.

I'll close this issue off for now but let me know if there's anything further I can help with.
