### ISSUE TITLE
kafka advertised listeners commans

### ISSUE THREAD

**Issue by Raawaan** [sleighzy/ansible-kafka#17]
Hello,

i'm trying to add  ''kafka_advertised_listeners" for each node in my custom inventory file
example:
0.0.0.0 zookeeper_id=1 kafka_broker_id=1 **kafka_advertised_listeners='PLAINTEXT://HOSTNAME:9092'**

and the output value in server.properties file is separeting each letter with a comma!
output example:
**advertised.listeners=P,L,A,I,N,T,E,X,T,:,/,/H,O,S,T,N,A,M,E:,9,0,9,2**

it works fine when adding the var to the main file anyway.

thanks.

**Comment by sleighzy** [comment]
Hi @Raawaan 

The `kafka_advertised_listeners` var should be a list, your current example shows this as a single string. Based on some examples of INI-style inventory files like your example (vs a yaml file) I believe it should look like the below, note the outer double quotes and array to represent the list. 

`kafka_advertised_listeners=“['PLAINTEXT://HOSTNAME:9092']”`

Note that I haven’t personally tested this, but hopefully helps out.

**Comment by sleighzy** [comment]
…the above comment was done on my phone and the double quotes `“”` show up as “smart quotes” so be mindful if you copy’n’paste them to use proper double quotes.

**Comment by Raawaan** [comment]
it's working now, thank you :D
