### ISSUE TITLE
generalized config params kafka_config_params

### ISSUE THREAD

**Issue by ObjectiveTruth** [sleighzy/ansible-kafka#28]
similar to https://github.com/sleighzy/ansible-zookeeper/issues/39

PR is #27

**Comment by ObjectiveTruth** [comment]
Seems to be failing on the molecule dependency installation. I'm not very familiar with Molecule or Github actions. Any advice on what might be happening? @sleighzy

**Comment by sleighzy** [comment]
Hi @ObjectiveTruth  What’s the error you’re seeing? I see after running the GitHub action just now that it errors out about not being able to find the ZooKeeper role. Is this the same problem you’re having, ie it’s missing a dependency, which is the ZooKeeper role?

**Comment by sleighzy** [comment]
Closing this issue now as #33 has superseded this.

I have also recently updated the dependencies and Molecule tests (and associated README docs on this) so all GitHub Actions and local test runs are now passing and this should resolve the previous issues noted in the comments above.

**Comment by sleighzy** [comment]
Closing as functionality has been implemented.
