### ISSUE TITLE
sleighzy.zookeeper - Version 3.9.1 is no longer available and fails when `molecule converge`  is run

### ISSUE THREAD

**Issue by samarthya** [sleighzy/ansible-kafka#41]
When you run molecule converge on the integration branch it fails due to unavailablity of the required version. The role sleighzy.zookeeper/defaults/main.yaml  defines the variable 

```yaml
zookeeper_version: 3.9.1
```

<img width="522" alt="Screenshot 2024-08-28 at 3 31 17 PM" src="https://github.com/user-attachments/assets/68d00f39-0e78-4cea-8492-5ca1dd4782f4">

```bash
TASK [sleighzy.zookeeper : Download Apache ZooKeeper] **************************
fatal: [server-3]: FAILED! => {"changed": false, "dest": "/tmp", "elapsed": 0, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 220, "state": "directory", "status_code": 404, "uid": 0, "url": "https://dlcdn.apache.org/zookeeper/zookeeper-3.9.1/apache-zookeeper-3.9.1-bin.tar.gz"}
fatal: [server-1]: FAILED! => {"changed": false, "dest": "/tmp", "elapsed": 0, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 180, "state": "directory", "status_code": 404, "uid": 0, "url": "https://dlcdn.apache.org/zookeeper/zookeeper-3.9.1/apache-zookeeper-3.9.1-bin.tar.gz"}
fatal: [server-2]: FAILED! => {"changed": false, "dest": "/tmp", "elapsed": 0, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 220, "state": "directory", "status_code": 404, "uid": 0, "url": "https://dlcdn.apache.org/zookeeper/zookeeper-3.9.1/apache-zookeeper-3.9.1-bin.tar.gz"}
```

**Comment by sleighzy** [comment]
@samarthya , thanks for the report. I have another ansible role for ZooKeeper so I'll need to bump and publish that, and then update this role appropriately for that version. Apologies in advance if this is blocking your current work.

**Comment by samarthya** [comment]
@sleighzy Nothing blocking I manually changed the local version and it was working. If we can add some variables to override or specify a defined version it would've been handy. Thank you for responding quickly!

**Comment by sleighzy** [comment]
@samarthya , I've released an updated version of that Ansible ZooKeeper role which now uses the latest 3.9.2 version so should resolve this. The ZooKeeper role does have a variable to specify the version to download, I'll need to update the README in this repository to give guidance for future reference as to how to override this in the tests.

**Comment by sleighzy** [comment]
I've made an additional change to the tests as well due to a breaking change introduced with Ansible core 2.12 + RHEL8 + Python 3.6.
